name: Publish

on:
    push:
        branches:
            - "main"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-node@v3
              with:
                  node-version: 18.x

            - run: npm install

            - run: npm run ci

            - name: Get Coverage for badge
              run: |
                  SUMMARY="$(npm run coverage | tail -2 | head -1)"
                  TOKENS=($SUMMARY)
                  echo "COVERAGE=$(echo ${TOKENS[2]})" >> $GITHUB_ENV

                  BRANCH_NAME="${PATHS[1]}_${PATHS[2]}"
                  echo $BRANCH_NAME
                  echo "BRANCH=$(echo ${BRANCH_NAME})" >> $GITHUB_ENV
        
            - name: Create the Badge
              uses: schneegans/dynamic-badges-action@v1.0.0
              with:
                auth: ${{ secrets.GIST_SECRET }}
                gistID: cae78aa41f0e72f261e01fd2fcee51f4
                filename: schema-transformer.json
                label: Test Coverage
                message: ${{ env.COVERAGE }}
                color: green
                namedLogo: vitest

            - name: Create PR
              id: changesets
              uses: changesets/action@v1
              with:
                  publish: npm run publish
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
